config/routes.rb
Rails.application.routes.draw do
  root "shops#index"
  get "shops/show"
  resources :products
  resources :order_items
  resources :carts, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items

  before_save :set_subtotal

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? (order_item.unit_price * order_item.quantity) : 0 }.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total_price
    self[:total] = quantity * set_unit_price
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_params)
    respond_to do |format|
      if @order.save
        format.js { render js: "window.top.location.reload(true);" }
      end
    end
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    respond_to do |format|
      if @order_item.update_attributes(order_params)
        format.js { render js: "window.top.location.reload(true);" }
      end
    end
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    respond_to do |format|
      if @order_item.destroy
        format.js { render js: "window.top.location.reload(true);" }
      end
    end
    @order_items = @order.order_items
  end

  private

  def order_params
    params.require(:order_item).permit(:product_id, :quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :price, :description)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def show
    @products = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/carts/_cart.html.erb
<%= link_to 'carts/show' do %>
  <button type="button" class="btn btn-outline-secondary cart">
    <i class="fa fa-shopping-cart"></i>
    <%= current_order.order_items.size %>
  </button>
<% end %>

app/views/carts/_cart_item.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<div class="panel-body">
  <% if @order_items.size>0 %>
    <% @order_items.each do |item| %>
      <div class="row">
        <div class="col-sm-2">
          <%# <%= image_tag item.product.image.url, class: "img-responsive" if item.product.image? %> %>
        </div>
        <div class="col-sm-6">
          <h4 class="product-name"><%= item.product.title.capitalize %></h4>
          <h4><small>$<%= item.product.price %></small></h4>
        </div>
        <div class="col-sm-4">
          <%= form_for(item, remote: true) do |f| %>
            <%= f.hidden_field :product_id, value: item.product.id %>
            <div class="row text-right">
              <h6><strong>Amount: $<%= item.total %></strong></h6>
            </div>
            <div class="row">
              <div class="col-md-4">
                <%= f.text_field :quantity, value: item.quantity.to_i, min: 1, class: 'form-control' %>
              </div>
              <div class="col-md-4">
                <%= f.submit "Add", class: 'btn btn-primary' %>
              </div>
              <div class="colo-md-3">
                <%= link_to "x", item, method: :delete, remote: true, class: 'fa fa-trash'  %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <hr>
    <% end %>
  <% else %>
    <h3>No items in the cart</h3>
  <% end %>
</div>

app/views/carts/show.html.erb
<div class="container mt-5 mb-5">
  <div class="row">
    <div class="col-md">
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="panel-title">
            <div class="row">
              <div class="col-md-6">
                <h5><span class="fa fa-shopping-cart"></span> Shopping Cart</h5>
              </div>
              <div class="col-md-6">
                <%# <button type="button" class="btn btn-primary">
                  <span class="fa fa-share-alt"></span> Continue shopping
                </button> %>
              </div>
            </div>
          </div>
        </div>
        <%= render "carts/cart_item" %>
        <div class="panel-footer">
          <div class="row text-center">
            <div class="col-md-9">
              <h4 class="text-right">Total $<%= current_order.subtotal %></h4>
            </div>
            <div class="col-md-3">
              <% if @order_items.size>0 %>
                <%# <%= link_to 'Checkout', new_order_path, class: "btn btn-success btn-block" %> %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/order_items/create.js.erb
$("#cart").html("<%= escape_javascript(render ('carts/cart')) %>")

app/views/order_items/update.js.erb
$("#cart").html("<%= escape_javascript(render ('carts/cart')) %>")
$("#cart_item").html("<%= escape_javascript(render ('carts/cart_item')) %>")

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Products</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Description</th>
      <th>
        <div id="cart">
          <%= render 'carts/cart' %>
        </div>
      </th>
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td>
          <%= form_for @order_item, remote: true do |f| %>
            <%= f.hidden_field :product_id, value: product.id %>
            <div class="price mt-1">$<%= product.price %></div>
            <div class="form-group">
              <%= f.text_field :quantity, value: 1, min: 1, class: 'form-control' %>
            </div>
            <%= f.submit "Add to cart", class: 'btn btn-primary btn-sm' %>
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Product', new_product_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>